name: sk-project
functions:
- name: get-data
  spec:
    kind: job
    metadata:
      name: get-data
      tag: ''
      project: sk-project
    spec:
      command: ''
      args: []
      image: .mlrun/remote-image
      env: []
      default_handler: handler
      entry_points:
        handler:
          name: handler
          doc: Query data from KV table via Presto.
          parameters:
          - name: context
            default: ''
          - name: v3io_username
            default: ''
          - name: v3io_access_key
            default: ''
          - name: presto_api
            default: ''
          - name: presto_table
            default: ''
          outputs:
          - default: ''
          lineno: 5
      description: ''
      build:
        functionSourceCode: aW1wb3J0IHBhbmRhcyBhcyBwZApmcm9tIHB5aGl2ZSBpbXBvcnQgcHJlc3RvCgoKZGVmIGhhbmRsZXIoY29udGV4dCwgdjNpb191c2VybmFtZSwgdjNpb19hY2Nlc3Nfa2V5LCBwcmVzdG9fYXBpLCBwcmVzdG9fdGFibGUpOgogICAgIiIiCiAgICBRdWVyeSBkYXRhIGZyb20gS1YgdGFibGUgdmlhIFByZXN0by4KICAgICIiIgogICAgY29udGV4dC5sb2dnZXIuaW5mbygiQ29ubmVjdGluZyB0byBQcmVzdG8iKQogICAgcmVxX2t3ID0gewogICAgICAgICJhdXRoIjogKHYzaW9fdXNlcm5hbWUsIHYzaW9fYWNjZXNzX2tleSksCiAgICAgICAgInZlcmlmeSI6IEZhbHNlLAogICAgfQogICAgY29ubiA9IHByZXN0by5jb25uZWN0KAogICAgICAgIHByZXN0b19hcGksCiAgICAgICAgcG9ydD00NDMsCiAgICAgICAgdXNlcm5hbWU9djNpb191c2VybmFtZSwKICAgICAgICBwcm90b2NvbD0iaHR0cHMiLAogICAgICAgIHJlcXVlc3RzX2t3YXJncz1yZXFfa3csCiAgICApCiAgICBjb250ZXh0LmxvZ2dlci5pbmZvKCJRdWVyeWluZyBQcmVzdG8iKQogICAgZGYgPSBwZC5yZWFkX3NxbF9xdWVyeShmInNlbGVjdCAqIGZyb20ge3ByZXN0b190YWJsZX0iLCBjb25uKQoKICAgIGNvbnRleHQubG9nZ2VyLmluZm8oIkxvZ2dpbmcgRGF0YXNldCIpCiAgICBjb250ZXh0LmxvZ19kYXRhc2V0KCJkYXRhIiwgZGY9ZGYsIGZvcm1hdD0iY3N2IiwgaW5kZXg9RmFsc2UpCg==
        commands: []
        code_origin: https://github.com/marcelonyc/igzambyint.git#00b658db825d9a23aa72344ae8edf829cfa61762:./remote_development/remote_example/project/data.py
- name: train-model
  spec:
    kind: job
    metadata:
      name: train-model
      tag: ''
      project: sk-project
    spec:
      command: ''
      args: []
      image: .mlrun/remote-image
      env: []
      default_handler: handler
      entry_points:
        handler:
          name: handler
          doc: Train SKLearn SVC Classifier with Iris Dataset.
          parameters:
          - name: context
            default: ''
          outputs:
          - default: ''
          lineno: 10
      description: ''
      build:
        functionSourceCode: ZnJvbSBjbG91ZHBpY2tsZSBpbXBvcnQgZHVtcHMKZnJvbSBtbHJ1biBpbXBvcnQgZ2V0X29yX2NyZWF0ZV9jdHgKaW1wb3J0IHBhbmRhcyBhcyBwZApmcm9tIHNrbGVhcm4uZGF0YXNldHMgaW1wb3J0IGxvYWRfaXJpcwpmcm9tIHNrbGVhcm4uc3ZtIGltcG9ydCBTVkMKZnJvbSBza2xlYXJuLm1ldHJpY3MgaW1wb3J0IGFjY3VyYWN5X3Njb3JlLCBmMV9zY29yZQpmcm9tIHNrbGVhcm4ucHJlcHJvY2Vzc2luZyBpbXBvcnQgTGFiZWxFbmNvZGVyCgoKZGVmIGhhbmRsZXIoY29udGV4dCk6CiAgICAiIiIKICAgIFRyYWluIFNLTGVhcm4gU1ZDIENsYXNzaWZpZXIgd2l0aCBJcmlzIERhdGFzZXQuCiAgICAiIiIKCiAgICAjIExvYWQgdmFsdWVzL3BhcmFtcyBmcm9tIE1MUnVuIGNvbnRleHQKICAgIHByaW50KGYiUnVuOiB7Y29udGV4dC5uYW1lfSAodWlkPXtjb250ZXh0LnVpZH0pIikKCiAgICAjIExvYWQgZGF0YQogICAgZGYgPSBjb250ZXh0LmlucHV0c1siZGF0YSJdLmFzX2RmKCkKICAgIFggPSBkZi5kcm9wKFsiaWQiLCAiY2xhc3MiXSwgYXhpcz0xKS52YWx1ZXMKICAgIHkgPSBMYWJlbEVuY29kZXIoKS5maXRfdHJhbnNmb3JtKGRmWyJjbGFzcyJdKQoKICAgICMgTUwgdHJhaW5pbmcgY29kZQogICAgY2xmID0gU1ZDKCkuZml0KFgsIHkpCiAgICB5X3ByZWQgPSBjbGYucHJlZGljdChYKQoKICAgICMgTG9nIG1ldHJpY3MgdG8gTUxSdW4gREIKICAgIGFjYyA9IGFjY3VyYWN5X3Njb3JlKHksIHlfcHJlZCkKICAgIGYxID0gZjFfc2NvcmUoeSwgeV9wcmVkLCBhdmVyYWdlPSJtaWNybyIpCiAgICBjb250ZXh0LmxvZ19yZXN1bHQoImFjY3VyYWN5IiwgYWNjKQogICAgY29udGV4dC5sb2dfcmVzdWx0KCJmMV9zY29yZSIsIGYxKQogICAgY29udGV4dC5zZXRfbGFiZWwoImZyYW1ld29yayIsICJza2xlYXJuIikKCiAgICAjIExvZyBtb2RlbCB0byBNTFJ1biBEQgogICAgY29udGV4dC5sb2dfbW9kZWwoCiAgICAgICAgImNsZiIsCiAgICAgICAgYm9keT1kdW1wcyhjbGYpLAogICAgICAgIG1vZGVsX2ZpbGU9Im1vZGVsLnBrbCIsCiAgICAgICAgbWV0cmljcz17ImFjY3VyYWN5IjogYWNjfSwKICAgICAgICBwYXJhbWV0ZXJzPWNsZi5nZXRfcGFyYW1zKCksCiAgICAgICAgbGFiZWxzPXsiZnJhbWV3b3JrIjogInNrbGVhcm4ifSwKICAgICkK
        commands: []
        code_origin: https://github.com/marcelonyc/igzambyint.git#00b658db825d9a23aa72344ae8edf829cfa61762:./remote_development/remote_example/project/training.py
workflows:
- name: main
  path: pipeline.py
artifacts: []
artifact_path: ''
